server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        # 'api' matches the service name in docker-compose.yaml
        proxy_pass http://api:9173;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}